FROM toposoid/scala-base:3.3.6

ARG TARGET_BRANCH
ARG AKKA_TOKEN
WORKDIR /app

ENV DEPLOYMENT=local

RUN apt-get update \
&& apt-get -y install git unzip \
&& git clone https://github.com/toposoid/scala-common.git \
&& cd scala-common \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sbt publishLocal \
&& rm -Rf ./target \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-knowledgebase-model.git \
&& cd toposoid-knowledgebase-model \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sbt publishLocal \
&& rm -Rf ./target \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-deduction-protocol-model.git \
&& cd toposoid-deduction-protocol-model \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sbt publishLocal \
&& rm -Rf ./target \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-common.git \
&& cd toposoid-common \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& export TOPOSOID_AKKA_TOKEN=${AKKA_TOKEN} \
&& sbt publishLocal \
&& export TOPOSOID_AKKA_TOKEN="" \
&& rm -Rf ./target \
&& mkdir -p /root/.m2/repository \
&& cp -rf ~/.cache/coursier/v1/https/repo.akka.io/${AKKA_TOKEN}/secure/* /root/.m2/repository/


