name: Build
on:
  workflow_call:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-scala-lib
  PJ_BRANCH: feature
  PJ_VERSION: 0.7-SNAPSHOT
jobs:
  build-toposoid-scala-lib:
    runs-on: ubuntu-24.04
    steps:
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
