name: Build
on:
  push:
    branches:
      - feature
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-scala-lib
  PJ_BRANCH: feature
  PJ_VERSION: 0.7-SNAPSHOT
jobs:
  build-toposoid-scala-lib-base-amd64:
    uses: ./.github/workflows/action-base-build-push-amd64.yml
    secrets: inherit  
  build-toposoid-scala-lib-base-arm64:
    needs: build-toposoid-scala-lib-base-amd64 
    uses: ./.github/workflows/action-base-build-push-arm64.yml
    secrets: inherit  
  merge-and-push-base-manifest:
    needs: build-toposoid-scala-lib-base-amd64 
    run: |  
      uname -m